### ISSUE TITLE
Fel namn på spelet på registreringssidan

### ISSUE THREAD

**Issue by derantell** [andersgranberg/gameplanhockeymanager-issues#1]
![your_team_-_game_plan_hockey_manager](https://cloud.githubusercontent.com/assets/2452594/4991786/7272835a-6998-11e4-8c09-3b431b4fe619.png)

**Comment by marcuslindblom** [comment]
Den hittade jag med! :)

**Comment by andersgranberg** [comment]
Fixat nu
