### ISSUE TITLE
Köpa spelare ifrån andra lag

### ISSUE THREAD

**Issue by kneeclass** [andersgranberg/gameplanhockeymanager-issues#18]
Genom att modifiera querystringen playerId till ett annat id så är det möjligt att lägga bud på spelare man ej bör kunna lägga bud på.

POST http://www.gameplanhockey.com/player/offercontract/ HTTP/1.1
Host: www.gameplanhockey.com
Connection: keep-alive
Content-Length: 130
Accept: _/_
Origin: http://www.gameplanhockey.com
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://www.gameplanhockey.com/player?gpid=1259
Accept-Encoding: gzip,deflate
Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4

contractSalary=37400&contractLength=2&contractClause_0=releaseonrelegation&playerId=players/1259&X-Requested-With=XMLHttpRequest

Ändra bara players/1259 till ett annat id så kommer ett köpförslag att läggas.

**Comment by andersgranberg** [comment]
Grymt viktigt info! Stort tack. Dock blir det ingen Pelikan för din del, en patch är på plats nu :P
