### ISSUE TITLE
Konstig sortering av playoff-matcher under Player - Form

### ISSUE THREAD

**Issue by derantell** [andersgranberg/gameplanhockeymanager-issues#28]
I **Last 5 Games** under **Player**, **Form** visas playoff-matcherna i ordningen **senast sist**, medan säsongsmatcherna visas **senast först**.

![joachim_haglund_-_game_plan_hockey_manager](https://cloud.githubusercontent.com/assets/2452594/5462303/d4fdec8a-8572-11e4-9c03-f20d74724110.png)

**Comment by andersgranberg** [comment]
Snyggt upptäckt! =)
