### ISSUE TITLE
Egenskapsvy under Roster

### ISSUE THREAD

**Issue by derantell** [andersgranberg/gameplanhockeymanager-issues#4]
Jag skulle vilja ha en vy av tabellen under **Roster** som visar spelarnas egenskaper, gärna sorterbara. Man skulle t.ex. kunna toggla mellan nuvarande vy och egenskapsvy. 

Känner att jag får hoppa omkring mycket mellan olika vyer när jag försöker "lära känna" spelarna.

**Comment by andersgranberg** [comment]
Mycket bra förslag!
