### ISSUE TITLE
Se vilken taktik man använt under en match

### ISSUE THREAD

**Issue by derantell** [andersgranberg/gameplanhockeymanager-issues#8]
För att kunna ta bättre beslut i framtiden skulle jag som manager vilja kunna se exakt vilken taktik jag använt i en tidigare match. 
- Reglar, special, focus tactics
- Line settings per line

Skulle även vara smutt om man kunde skriva lite anteckningar om en match som man senare kan gå tillbaka till.

![copper_mountain_lumberjacks_vs_huntland_barons__game_1](https://cloud.githubusercontent.com/assets/2452594/5057853/326d4590-6cd8-11e4-89f3-7ef0192c05d5.png)

**Comment by andersgranberg** [comment]
Grymt förslag!
